[package]
name = "kfree_skb_net"
version = "0.1.0"
edition.workspace = true

license.workspace = true

[dependencies]
kfree_skb-common = { path = "../kfree_skb-common", features = ["user"] }
kfree_skb_net-ebpf = { path = "../kfree_skb_net-ebpf" }

anyhow = { workspace = true, default-features = true }
aya = { workspace = true }
aya-log = { workspace = true }
env_logger = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
    "time",
    "fs",
] }
tokio-util = { version = "0.7", default-features = false, features = ["compat"] }
serde = { workspace = true }
axum = { version = "0.7", default-features = false, features = ["json", "tokio", "http1"] }

[build-dependencies]
anyhow = { workspace = true }
aya-build = { workspace = true }
cargo_metadata = { workspace = true }

[[bin]]
name = "kfree_skb_net"
path = "src/main.rs"
