[package]
name = "bpfagent"
version = "0.1.0"
edition = "2021"
description = "EBPF program manager and Prometheus metrics extractor"
license = "MIT OR Apache-2.0"
repository = "https://github.com/katim/bpfagent"
homepage = "https://github.com/katim/bpfagent"
keywords = ["ebpf", "bpf", "network", "monitoring", "prometheus"]
categories = ["network-programming", "development-tools"]

[[bin]]
name = "bpfagent"
path = "src/main.rs"

[dependencies]
aya = { workspace = true, default-features = false }
aya-log = { workspace = true, default-features = false }
clap = { workspace = true }
libc = { workspace = true, default-features = false }
tokio = { workspace = true, features = ["full", "signal"] }
tokio-util = { workspace = true, features = ["rt"] }
log = { workspace = true }
env_logger = { version = "0.11.5", default-features = false, features = ["default"] }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
prometheus = { workspace = true, default-features = false, features = ["process"] }
kfree_skb-common = { path = "../common/kfree_skb" }
sca-common = { path = "../common/sca", features = ["user"] }
procfs = { version = "0.15", default-features = false }

[dev-dependencies]
rand = "0.9"

[build-dependencies]
aya-build = { workspace = true }
cargo_metadata = { workspace = true }
anyhow = { workspace = true, default-features = false }

[package.metadata.deb]
name = "bpfagent"
maintainer = "Katim LLC <contact@katim.io>"
section = "net"
priority = "optional"
depends = "$auto"
conf-files = ["/etc/bpfagent.conf"]
suggests = "libbpf1, libelf1"
extended-description = """EBPF program manager and Prometheus metrics extractor

A daemon that loads EBPF programs and exposes metrics to Prometheus."""